[tool.poetry]
name = "hypster"
<<<<<<< HEAD
version = "0.1.6"
description = "A flexible configuration system for Python projects"
=======
version = "0.1.5"
description = "A lightweight configuration system for AI & Machine Learning projects"
>>>>>>> fa2052a77ae1d2a301d850eb329c317e6fae43d9
authors = ["Gilad Rubin <gilad.rubin@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/hypster-dev/hypster"
keywords = ["configuration", "ai", "machine-learning"]

[tool.poetry.dependencies]
python = "^3.10"
networkx = "^2.6"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
ruff = "^0.1.0"
mypy = "^0.950"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.mypy]
ignore_missing_imports = true
strict_optional = true