# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SEED": "05_sklearn.ipynb",
         "auto_assign": "02_oo_hp.ipynb",
         "HypsterBase": "02_oo_hp.ipynb",
         "HpExpression": "02_oo_hp.ipynb",
         "HYPSTER_TYPES": "02_oo_hp.ipynb",
         "SubExpression": "02_oo_hp.ipynb",
         "AddExpression": "02_oo_hp.ipynb",
         "MulExpression": "02_oo_hp.ipynb",
         "DivExpression": "02_oo_hp.ipynb",
         "PowExpression": "02_oo_hp.ipynb",
         "HpInt": "02_oo_hp.ipynb",
         "HpFloat": "02_oo_hp.ipynb",
         "HpFunc": "02_oo_hp.ipynb",
         "HpCategorical": "02_oo_hp.ipynb",
         "HpVarLenList": "02_oo_hp.ipynb",
         "list_to_tuple": "02_oo_hp.ipynb",
         "populate_iterable": "02_oo_hp.ipynb",
         "populate_dict": "02_oo_hp.ipynb",
         "HpList": "02_oo_hp.ipynb",
         "HpTuple": "02_oo_hp.ipynb",
         "HpDict": "02_oo_hp.ipynb",
         "HpBool": "02_oo_hp.ipynb",
         "HpToggle": "02_oo_hp.ipynb",
         "DATA_STRUCTURES": "02_oo_hp.ipynb",
         "contains_hypster": "02_oo_hp.ipynb",
         "sample_hp": "02_oo_hp.ipynb",
         "run_hp_test": "02_oo_hp.ipynb",
         "HypsterPrepare": "03_hypster_prepare.ipynb",
         "prepare": "03_hypster_prepare.ipynb",
         "run_func_test": "03_hypster_prepare.ipynb",
         "path": "05_sklearn.ipynb",
         "df": "05_sklearn.ipynb",
         "cat_names": "05_sklearn.ipynb",
         "cont_names": "05_sklearn.ipynb",
         "dep_var": "05_sklearn.ipynb",
         "Normalize": "04_tabular_api.ipynb",
         "norm": "04_tabular_api.ipynb",
         "procs": "04_tabular_api.ipynb",
         "to": "04_tabular_api.ipynb",
         "dls": "04_tabular_api.ipynb",
         "cbs": "04_tabular_api.ipynb",
         "start_mom": "04_tabular_api.ipynb",
         "tabular_learner": "04_tabular_api.ipynb",
         "learner": "04_tabular_api.ipynb",
         "run_learner": "05_sklearn.ipynb",
         "study": "05_sklearn.ipynb"}

modules = ["oo_hp.py",
           "hypster_prepare.py",
           "tabular_api.py",
           "sklearn.py"]

doc_url = "https://hypster-dev.github.io/hypster/"

git_url = "https://github.com/hypster-dev/hypster/tree/master/"

def custom_doc_links(name): return None
