# AUTOGENERATED! DO NOT EDIT! File to edit: 04_tabular_api.ipynb (unless otherwise specified).

__all__ = ['run_func_test']

# Cell
from .oo_hp import *
from .hypster_prepare import *

# Cell
def run_func_test(x, n_trials=5):
    def objective(trial):
        x.sample(trial)
        return 1.0

    optuna.logging.set_verbosity(0)
    pruner = optuna.pruners.NopPruner()
    study = optuna.create_study(direction="maximize", pruner=pruner)
    study.optimize(objective, n_trials=n_trials, timeout=600)